### ISSUE TITLE
Does not appear to be adding items to config file when using commands

### ISSUE THREAD

**Issue by Zygus42** [mactso/HappyTrails#2]
Trying to use /happytrails setHappyTrailSpeed 2, and it does not appear to do anything.  See picture:
![2021-05-04_10 57 57](https://user-images.githubusercontent.com/20757445/116956416-cfd14580-acc7-11eb-81e6-78b7bf78aa1a.png)

I'm in Creative mode and using HappyTrails-1.16.5-1.36.0.8

**Comment by Zygus42** [comment]
Woops never mind.  Thought it would change the file I had on defaultconfigs, instead is changing file in save/serverconfig.

**Comment by mactso** [comment]
Thank you !   It's odd because I thought I had moved all of our configs /serverconfig to /config.
Glad you got it working but I need to fix this because I've found out that /serverconfig files are more difficult to work with when building modpacks.

**Comment by Zygus42** [comment]
Yep - they're a real pain when you're building modpacks.

**Comment by mactso** [comment]
Are you using 1.16?   Planning on checking this and changing it within the week if it is still in serverconfig.

**Comment by Zygus42** [comment]
Yep.  1.16.5.  Just building a private modpack.
